### ISSUE TITLE
Locations of signal boxes

### ISSUE THREAD

**Issue by mobile-appz** [mikeqfu/pyrcs#3]
Hi, this looks like a great resource. Just wondering if there is any way to derive the geographical location in latitude and longitude (ie not just ELR) of the UK signal boxes. Thanks.

**Comment by mikeqfu** [comment]
Hi @mobile-appz, The package only scrapes the data that is available on the Railway Codes website. I'm afraid the website currently does not has the information of signal boxes latitude/longitude. You might have to contact directly the authorities (e.g. such as Network Rail) for that data, or try to [make a FOI request](https://www.gov.uk/make-a-freedom-of-information-request).
